### ISSUE TITLE
Test failures from Raspberry Pi

### ISSUE THREAD

**Issue by bingos** [perl5-utils/List-MoreUtils#12]
I've seen 1 subtest fail on Raspberry Pi (both Linux and FreeBSD) (both RPi B and RPi 2).

http://www.cpantesters.org/cpan/report/1f89881e-2234-11e5-a85a-e28fcaadd3a7
http://www.cpantesters.org/cpan/report/564d1942-2239-11e5-a85a-e28fcaadd3a7
(There will an arm-freebsd one at some point too).

I stuck an 'or diag($@)' on the failing test and got the following:

not ok 360
# Failed test at t/lib/LMU/Test/Functions.pm line 1229.
# Modification of non-creatable array value attempted, subscript 0 at /home/pi/List-MoreUtils-0.413/blib/lib/List/MoreUtils/PP.pm line 476.

**Comment by rehsack** [comment]
Are you sure that this is an L::MU issue? Seems there is an automatic correction of "index" which isn't right there.

**Comment by rehsack** [comment]
ETIMEDOUT :P
