### ISSUE TITLE
.git may be present in user mode

### ISSUE THREAD

**Issue by richardipsum** [perl5-utils/List-MoreUtils#14]
Hello :)

commit 684c42a8a52594d00335ef82d825e7a91693e250 adds a test which uses the presence of a .git directory to distinguish between author and user mode. We work with a system that takes release tarballs from CPAN and converts them to git repositories. List-MoreUtils in particular fails to build in our environment because the tarball on CPAN doesn't have the Sandbox::Tumble module that the Makefile.PL expects to find if there is a .git directory. Would it be possible to make this test for author mode more specific to your source repository? Perhaps this could be done by adding a tag to the source repo that won't be present in the CPAN release tarball and have the Makefile.PL test for the existence of that tag as well as the existence of a .git directory?

Many thanks,
Richard Ipsum

**Comment by rehsack** [comment]
The entire code is introduced because of the trouble in #9 and #11 

Personally I think, the new code is worse than expecting a reasonable configure stage.

Is GIT_DIR not a reasonable workaround?

**Comment by richardipsum** [comment]
Hi! Sorry I don't understand the question. Can you elaborate?

**Comment by rehsack** [comment]
https://git-scm.com/blog/2010/04/11/environment.html

**Comment by richardipsum** [comment]
Hrm, perhaps I misunderstand, but the issue here is really that you cannot assume that the presence of a directory named ".git" means that you're in "author" mode. I'm not sure how GIT_DIR would solve this.

**Comment by rehsack** [comment]
Well - it is a suitable way.

> The .git directory does not even need to actually be within your project. Git allows you to tell it where your .git directory is ...

Just don't have a .git directory in the project dir, it is easy for you to solve that.

Try to convince me why it is unacceptable for you to move the .git directory to somewhere else and ask me to spend my spare time find another solution.

**Comment by kentfredric** [comment]
I suspect they're doing something like  [Git::CPAN::Patch](https://metacpan.org/release/Git-CPAN-Patch) does, which makes it impossible to change where the git directory is.

Because you're mirroring upstream tarballs in commits-per-release pattern.

"Just change" may not even be an option.

**Comment by rehsack** [comment]
They should explain - and if difficult, offer a suitable patch.
A patch which works on travis and without having git installed (local CI, NFS mounts).

**Comment by kentfredric** [comment]
"assume authormode if META.yml" has been a reasonable heuristic for some cases so far.

Given that the META.yml must be added to correctly publish the dist, and that Makefile.PL will generate the META.yml if one does not exist.

But there's a few other tricks harrg/distar does here that could be important. 

> https://metacpan.org/source/HAARG/Devel-Confess-0.008000/Makefile.PL#L6

**Comment by rehsack** [comment]
I thought about something like that, but as said - it costs me and might cause other issues...
To develop a clean, complete solution with tests etc. causes lot's of effort for maybe no reason.

@richardipsum should explain and seriously prove ...

**Comment by rehsack** [comment]
I created https://github.com/ambs/Config-AutoConf/issues/11 - even if I think this ticket smells for commercial support request.
