### ISSUE TITLE
Upgrading from LMU 0.416 to split XS/PP version will fail

### ISSUE THREAD

**Issue by haarg** [perl5-utils/List-MoreUtils#22]
Previous versions of List::MoreUtils would install into the arch directory, because they had an XS component.  With List::MoreUtils::XS being split into a separate dist, List::MoreUtils and List::MoreUtils::PP will be installed into the non-arch lib.

arch takes precedence, so if a user upgrades from 0.416 to a split PP/XS version, the new version will be shadowed by the old version and the new version won't be able to be loaded.

For other cases of this, we've had the make install process delete the old arch versions.  [Devel::GlobalDestruction](https://metacpan.org/source/HAARG/Devel-GlobalDestruction-0.14/Makefile.PL#L62-75) has an example of this.

**Comment by rehsack** [comment]
Thank you very much. I'll see how current push behaves in travis and will adopt your hint when testing on a blead-perl later.

**Comment by rehsack** [comment]
I hope this is done correctly now. I watch cpantesters...
Thanks again for pointing that out.

**Comment by rehsack** [comment]
@haarg - can you provide the fixed patch?
