### ISSUE TITLE
Please document your permission to change the license

### ISSUE THREAD

**Issue by shadowcat-mst** [perl5-utils/List-MoreUtils#24]
Relicensing normally requires permission from all prior contributors and I don't see anything demonstrating due diligence has been done here.

**Comment by rehsack** [comment]
I'll clarify in final release the the new license covers only code from 0.417 and above. Thanks for pointing that out.

**Comment by shadowcat-mst** [comment]
So the license is going to be "Artistic or GPL" *and* "Apache 2" ? This seems likely to annoy compliance departments.

**Comment by rehsack** [comment]
Well, it's likely true - but when people run around and publish code under their name without pointing out the source, it's unfortunately the only consequence. Open Source and Public Domain is a big difference.

**Comment by haarg** [comment]
What code has been published in List::MoreUtils without attribution?

**Comment by rehsack** [comment]
I'm not going to discuss those kinds of issues with you guys. I'm sorry. This war has been gone to far and I'm not willing to do it anymore. I continue this project and I'm happy about any technical issue reported and will fix anything which bothers people - but no discussion about permissions, attitude etc. anymore.

**Comment by shadowcat-mst** [comment]
This is a technical/legal issue;  please don't imagine personal attacks where none exist, you're discussing with us here, not arguing with riba.

**Comment by gregoa** [comment]
Trying to understand how this would work in practice: does this mean that old code lines would be under Artistic or GPL-1+, and newer commits under Apache-2.0? Or something different? This sounds at least confusing (if legally possible).

I'm fine with any free license, just trying to wrap my head around this question in order to be prepared for a next upload to Debian :)

**Comment by shadowcat-mst** [comment]
At the very least it would be helpful to call out the new license clearly in the docs so that people don't end up accidentally affected by this change across an upgrade - while this isn't a technical compat break, users should be made aware of the additional potential compliance issues so they have the option to switch to a normally licensed distribution if the compliance is a problem for them.

**Comment by rehsack** [comment]
@shadowcat-mst - since #9 and #11 I don't make there any difference anymore. If you want to change that, this is not the right place.
@gregoa - @shadowcat-mst phrased it correctly as "Artistic or GPL" and "Apache 2".

**Comment by karenetheridge** [comment]
I see the changelog says:

> - Change license to Apache 2.0 to avoid code stealing without credits

@rehsack can you clarify what you mean here? do you mean code stolen from LMU, or stolen from other sources and added to LMU? How would the Apache 2.0 licence help?

**Comment by gregoa** [comment]
@rehsack Thanks for the clarification. While I don't know if and how much headache this causes for our users (as in: what exactly is the result of this license combination?), `"License: Artistic or GPL-1+, and Apache-2.0"` [translated into our copyright format syntax], meaning "the files contain both Artistic-or-GPL-1+ and Apache-2 code", should work for us.

**Comment by rehsack** [comment]
@gregoa - the typical user just used the module and doesn't care those differences. The headache applies when you start derived work from such a module.

**Comment by haarg** [comment]
Can you explain the issue you have with attribution regarding List::Util and List::SomeUtils?  If there is a problem with attribution, we should work to resolve that no matter what you do with the license in this dist.

**Comment by rehsack** [comment]
Not here, not now. Maybe face to face. Let's keep on topic - the issuer was right, the point has been clarified.
