### ISSUE TITLE
PP/XS split needs to be fixed up.

### ISSUE THREAD

**Issue by shadowcat-mst** [perl5-utils/List-MoreUtils#26]
So, what *should* be the behaviour is (note I'm documenting the full list, not implying all of these are broken):

1) List::MoreUtils::XS can be installed on its own and use()d directly and works.

2) Installing List::MoreUtils with a compiler available should automatically also install List::MoreUtils::XS

3) Running List::MoreUtils' Makefile.PL with PUREPERL_ONLY set to a true value should supercede (2).

4) It would be *nice* if there was a way to suppress use of ::XS even when installed, but Devel::Hide/Test::Without::Module are sufficient for that purpose if you'd prefer not to add a specific feature.

Note that in earlier days, there was just one List::MoreUtils which built as pp or xs depending, so people could only depend directly on that, so you can't assume that people dependent on xs performance specify ::XS as well even if we skip the part where humans suck and never set stuff explicitly anyway.

**Comment by karenetheridge** [comment]
> Installing List::MoreUtils with a compiler available should automatically also install List::MoreUtils::XS

This also means that if LMU (the PP side) is being upgraded, then the XS side should also be upgraded -- so LMU $x should add a prereq for LMUXS $x.

**Comment by rehsack** [comment]
Guys - the only point was, that it never was a requirement. In contrast - at the moment I was discussing the reduction of the requirements of (max reduced) LMU, it was mentioned by one that explicitely requirement of List::MoreUtils::XS is reasonable and should be approached.

#25 made clear, that this was a special view and List::MoreUtils::XS should be able work alone and NOT depend on List::MoreUtils.

So - new requirement - unfortunately not during dev-release should be reviewed, so well, bad luck - but I realized that and think how to solve it reliable and soon. No need to presure by opening new tickets :P

**Comment by shadowcat-mst** [comment]
This is not pressure, I was trying to be explicit to avoid further miscommunication.

It was always a requirement. If you don't meet these requirements splitting the dists then the split dists are broken. We explained this years ago.

This is standard for split PP/XS dists. Please don't pretend it's special. It isn't.

**Comment by rehsack** [comment]
1st paragraph is fine. 2nd paragraph is debatable. 3rd paragraph is the reason not joining irc.perl.org at all. Calm down.

> This is not pressure, I was trying to be explicit to avoid further miscommunication.

You could be explicit in #25 without any trouble. I'm closing here (completely), any further (reasonable) questions and discussion can continue in #25.

**Comment by shadowcat-mst** [comment]
Damnit, I opened this one because YOU CLOSED #25.

Please re-open one of the issues, or we can create another one.

3rd paragraph is completely calm. You claimed special. I told you that you were wrong.

Please stop calling me "not calm" for pointing out that you are factually incorrect. YOu are being unreasonable.

**Comment by shadowcat-mst** [comment]
I fail to see how telling you it isn't special when you claimed "this was a special view" is an issue. If you don't want me to say something that isn't special isn't special ... don't claim that it's special.

Facts exist. Please keep calm and keep to the facts.

**Comment by rehsack** [comment]
As you realize, you can easily post to a closed issue and ask if it can be reopend because you have a point. Starting opening new issues because you think you're right is pressuring. Get it or not.

I did not claim being special - I claimed that the people thinking about how to split those modules explicitely wanted that kind of split.

**Comment by shadowcat-mst** [comment]
I opened a new issue because the previous one had started to become confused, and had already been closed. This is a common approach to achieivng a clarified, calmer discussion.

Claiming it's pressuring is disingenuous at best. Also, you still haven't re-opened either.

Is your last comment a lie, then?

**Comment by Grinnz** [comment]
He re-opened the other issue. Let's take it down a notch.
