### ISSUE TITLE
sort_by/nsort_by reverse versions

### ISSUE THREAD

**Issue by mike-hart** [perl5-utils/List-MoreUtils#28]
Hi, I note in 1e4ec43202b51af5f94deb5ad8fd5d483d3bf949 that sort_by and nsort_by were added from/equivalent-to List::UtilsBy

Is there a plan to also add the rev_* variants to avoid needing to reverse the results or (in the nsort case) invert the key?

**Comment by rehsack** [comment]
No. I think, List::UtilsBy is a great module and there is no plan to make List::MoreUtils another List::AllUtils.
