### ISSUE TITLE
Misprint in 'part BLOCK LIST' in POD

### ISSUE THREAD

**Issue by commojun** [perl5-utils/List-MoreUtils#30]
In POD,
http://search.cpan.org/~rehsack/List-MoreUtils-0.426/lib/List/MoreUtils.pm#part_BLOCK_LIST

> Negative values are only ok when they refer to a partition previously created:
> ``` perl
>   my @idx  = ( 0, 1, -1 );
>   my $i    = 0;
>   my @part = part { $idx[$++ % 3] } 1 .. 8; # [1, 4, 7], [2, 3, 5, 6, 8]
> ```

Is `$++` a misprint of `$i++` ?
https://github.com/perl5-utils/List-MoreUtils/blob/master/lib/List/MoreUtils.pm#L575

**Comment by rehsack** [comment]
Seems to be fixed without mentioning this issue
