### ISSUE TITLE
Macros introduced in dfd851147f cause problems with MSVC

### ISSUE THREAD

**Issue by nanis** [perl5-utils/List-MoreUtils#8]
See [test report](http://www.cpantesters.org/cpan/report/c7be9a11-6c76-1014-a8ab-43f4045ca49c).

`MoreUtils.xs` doesn't compile any more. I arrived at the specific commit using `git bisect`.

<pre>C:\...\src\List-MoreUtils> git bisect good
dfd851147f0861750f36e58cfac151b98cf8edc1 is the first bad commit
commit dfd851147f0861750f36e58cfac151b98cf8edc1
Author: Jens Rehsack <sno@netbsd.org>
Date:   Mon Mar 9 13:19:56 2015 +0100

    increase code-reuse for common loops

:100644 100644 810fcf052f3df7516ca297756ab771a5081dee47 05119f9b4a7424fbc87b06f385c6e7dc337e9158 M      MoreUtils.xs</pre>

I am afraid I am not able to offer more insight at the moment.

<pre> C:\> cl /?
Microsoft (R) C/C++ Optimizing Compiler Version 18.00.31101 for x64

C:\> perl -V
Summary of my perl5 (revision 5 version 20 subversion 2) configuration:
   
  Platform:
    osname=MSWin32, osvers=6.3, archname=MSWin32-x64-multi-thread
    uname=''
    config_args='undef'
    hint=recommended, useposix=true, d_sigaction=undef
    useithreads=define, usemultiplicity=define
    use64bitint=define, use64bitall=undef, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cl', ccflags ='-nologo -GF -W3 -O1 -Os -favor:INTEL64 -MD -Zi -DNDEBUG -GL -fp:precise -DWIN32 -D_CONSOLE -DNO_STRICT -DWIN64 -DCONSERVATIVE -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE  -DUSE_64_BIT_ALL -DPERL_TEXTMODE_SCRIPTS -DUSE_SITECUSTOMIZE -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DUSE_PERLIO',
    optimize='-O1 -Os -favor:INTEL64 -MD -Zi -DNDEBUG -GL -fp:precise',
    cppflags='-DWIN32'
    ccversion='18.00.31101', gccversion='', gccosandvers=''
    intsize=4, longsize=4, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=undef, longlongsize=8, d_longdbl=define, longdblsize=8
    ivtype='__int64', ivsize=8, nvtype='double', nvsize=8, Off_t='__int64', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='link', ldflags ='-nologo -nodefaultlib -debug -opt:ref,icf -ltcg  -libpath:"c:\opt\perl-5.20.2\lib\CORE"  -machine:AMD64 "/manifestdependency:type='Win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' processorArchitecture='*' publicKeyToken='6595b64144ccf1df' language='*'"'
    libpth="C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\lib\amd64"
    libs=oldnames.lib kernel32.lib user32.lib gdi32.lib winspool.lib  comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib  netapi32.lib uuid.lib ws2_32.lib mpr.lib winmm.lib  version.lib odbc32.lib odbccp32.lib comctl32.lib msvcrt.lib
    perllibs=oldnames.lib kernel32.lib user32.lib gdi32.lib winspool.lib  comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib  netapi32.lib uuid.lib ws2_32.lib mpr.lib winmm.lib  version.lib odbc32.lib odbccp32.lib comctl32.lib msvcrt.lib
    libc=msvcrt.lib, so=dll, useshrplib=true, libperl=perl520.lib
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_win32.xs, dlext=dll, d_dlsymun=undef, ccdlflags=' '
    cccdlflags=' ', lddlflags='-dll -nologo -nodefaultlib -debug -opt:ref,icf -ltcg  -libpath:"c:\opt\perl-5.20.2\lib\CORE"  -machine:AMD64 "/manifestdependency:type='Win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' processorArchitecture='*' publicKeyToken='6595b64144ccf1df' language='*'"'

Characteristics of this binary (from libperl): 
  Compile-time options: HAS_TIMES HAVE_INTERP_INTERN MULTIPLICITY
                        PERLIO_LAYERS PERL_DONT_CREATE_GVSV
                        PERL_HASH_FUNC_ONE_AT_A_TIME_HARD
                        PERL_IMPLICIT_CONTEXT PERL_IMPLICIT_SYS
                        PERL_MALLOC_WRAP PERL_NEW_COPY_ON_WRITE
                        PERL_PRESERVE_IVUV USE_64_BIT_ALL USE_64_BIT_INT
                        USE_ITHREADS USE_LARGE_FILES USE_LOCALE
                        USE_LOCALE_COLLATE USE_LOCALE_CTYPE
                        USE_LOCALE_NUMERIC USE_PERLIO USE_PERL_ATOF
                        USE_SITECUSTOMIZE
  Built under MSWin32
  Compiled at Feb 16 2015 08:44:56
  %ENV:
    PERLDOC_PAGER="c:\opt\cygwin64\bin\less.exe -+C -E -F -g -i"
  @INC:
    c:/opt/perl-5.20.2/site/lib/MSWin32-x64-multi-thread
    c:/opt/perl-5.20.2/site/lib
    c:/opt/perl-5.20.2/lib
    .
</pre>

**Comment by nanis** [comment]
#line 369 "MoreUtils.xs" { if(!codelike(code)) Perl_croak_xs_usage(cv, "code,
    ..."); if (items > 1) { SV **newsp; PERL_CONTEXT *cx; CV *multicall_cv; OP
    *multicall_cop; char multicall_oldcatch; U8 hasargs = 0; int i; HV *stash; GV
    *gv; CV *_cv; SV **args = &(((PerlInterpreter
    *)Perl_get_context())->Istack_base)[ax]; I32 gimme = 2; _cv =
    Perl_sv_2cv(((PerlInterpreter *)Perl_get_context()), code,&stash,&gv,0); do {
    CV * const _nOnclAshIngNamE_ = _cv; CV * const cv = _nOnclAshIngNamE_; PADLIST
    * const padlist = ((XPVCV*)((void *) ((cv)->sv_any)))->xcv_padlist;
    Perl_push_scope(((PerlInterpreter *)Perl_get_context())); multicall_oldcatch =
    ((((PerlInterpreter *)Perl_get_context())->Itop_env)->je_mustcatch);
    Perl_save_strlen(((PerlInterpreter *)Perl_get_context()), (STRLEN
    *)&(((PerlInterpreter *)Perl_get_context())->Itmps_floor)), (((PerlInterpreter
    *)Perl_get_context())->Itmps_floor) = (((PerlInterpreter
    *)Perl_get_context())->Itmps_ix); Perl_save_vptr(((PerlInterpreter
    *)Perl_get_context()), (void*)&((((PerlInterpreter
    *)Perl_get_context())->Iop))); do {  (((PerlInterpreter
    *)Perl_get_context())->Itop_env)->je_mustcatch = ((1)); } while (0); do {
    PERL_SI *next = (((PerlInterpreter
    *)Perl_get_context())->Icurstackinfo)->si_next;  if (!next) { next =
    Perl_new_stackinfo(((PerlInterpreter *)Perl_get_context()),
    32,2048/sizeof(PERL_CONTEXT) - 1); next->si_prev = (((PerlInterpreter
    *)Perl_get_context())->Icurstackinfo); (((PerlInterpreter
    *)Perl_get_context())->Icurstackinfo)->si_next = next; } next->si_type = 3;
    next->si_cxix = -1; ((XPVAV*) (next->si_stack)->sv_any)->xav_fill = 0; do {
    ((XPVAV*) ((((PerlInterpreter
    *)Perl_get_context())->Icurstack))->sv_any)->xav_fill = sp - (((PerlInterpreter
    *)Perl_get_context())->Istack_base); (((PerlInterpreter
    *)Perl_get_context())->Istack_base) = ((next->si_stack)->sv_u.svu_array);
    (((PerlInterpreter *)Perl_get_context())->Istack_max) = (((PerlInterpreter
    *)Perl_get_context())->Istack_base) + ((XPVAV*)
    (next->si_stack)->sv_any)->xav_max; sp = (((PerlInterpreter
    *)Perl_get_context())->Istack_sp) = (((PerlInterpreter
    *)Perl_get_context())->Istack_base) + ((XPVAV*)
    (next->si_stack)->sv_any)->xav_fill; (((PerlInterpreter
    *)Perl_get_context())->Icurstack) = next->si_stack; } while (0);
    (((PerlInterpreter *)Perl_get_context())->Icurstackinfo) = next; (void)0; }
    while (0); (((((PerlInterpreter *)Perl_get_context())->Icurstackinfo)->si_cxix)
    < ((((PerlInterpreter *)Perl_get_context())->Icurstackinfo)->si_cxmax) ?
    ++((((PerlInterpreter *)Perl_get_context())->Icurstackinfo)->si_cxix) :
    (((((PerlInterpreter *)Perl_get_context())->Icurstackinfo)->si_cxix) =
    Perl_cxinc(((PerlInterpreter *)Perl_get_context())))), cx =
    &((((PerlInterpreter
    *)Perl_get_context())->Icurstackinfo)->si_cxstack)[((((PerlInterpreter
    *)Perl_get_context())->Icurstackinfo)->si_cxix)], cx->cx_u.cx_subst.sbu_type =
    (8|0x10|0), cx->cx_u.cx_blk.blku_oldsp = (((PerlInterpreter
    *)Perl_get_context())->Istack_sp) - (((PerlInterpreter
    *)Perl_get_context())->Istack_base), cx->cx_u.cx_blk.blku_oldcop =
    (((PerlInterpreter *)Perl_get_context())->Icurcop),
    cx->cx_u.cx_blk.blku_oldmarksp = (((PerlInterpreter
    *)Perl_get_context())->Imarkstack_ptr) - (((PerlInterpreter
    *)Perl_get_context())->Imarkstack), cx->cx_u.cx_blk.blku_oldscopesp =
    (((PerlInterpreter *)Perl_get_context())->Iscopestack_ix),
    cx->cx_u.cx_blk.blku_oldpm = (((PerlInterpreter *)Perl_get_context())->Icurpm),
    cx->cx_u.cx_blk.blku_gimme = (U8)gimme; ;;; { U8 phlags = ( ((((PerlInterpreter
    *)Perl_get_context())->Iop)->op_flags & 3) ? (128|1) : !((((PerlInterpreter
    *)Perl_get_context())->Iop)->op_private & (128|1)) ? 0 :
    (U8)Perl_was_lvalue_sub(((PerlInterpreter *)Perl_get_context())) ); ;
    cx->cx_u.cx_blk.blk_u.blku_sub.cv = cv; cx->cx_u.cx_blk.blk_u.blku_sub.olddepth
    = (*S_CvDEPTHp((const CV *)cv)); cx->cx_u.cx_subst.sbu_type |= (hasargs) ? 0x20
    : 0; cx->cx_u.cx_blk.blk_u.blku_sub.retop = 0; if (!(*S_CvDEPTHp((const CV
    *)cv))) { (void)(++(((SV *)((void *) (cv))))->sv_refcnt); (void)(++(((SV
    *)((void *) (cv))))->sv_refcnt); Perl_save_pushptr(((PerlInterpreter
    *)Perl_get_context()), (void *)(((SV *)((void *) (cv)))),11); }
    cx->cx_u.cx_blk.blku_u16 = (((PerlInterpreter
    *)Perl_get_context())->Iop)->op_private & (phlags|(32|64)); }; if (!(0 & 0x80))
    (*S_CvDEPTHp((const CV *)cv))++; if ((*S_CvDEPTHp((const CV *)cv)) >= 2) {
    (void)0; Perl_pad_push(((PerlInterpreter *)Perl_get_context()), padlist,
    (*S_CvDEPTHp((const CV *)cv))); } Perl_save_pushptr(((PerlInterpreter
    *)Perl_get_context()), ((SV *)((void *) ((((PerlInterpreter
    *)Perl_get_context())->Icomppad)))),7); (((PerlInterpreter
    *)Perl_get_context())->Icomppad) = (PAD*)
    ((padlist)->xpadl_alloc[(*S_CvDEPTHp((const CV *)cv))]); (((PerlInterpreter
    *)Perl_get_context())->Icurpad) = (((((PerlInterpreter
    *)Perl_get_context())->Icomppad))->sv_u.svu_array); ;; multicall_cv = cv;
    multicall_cop = ((XPVCV*)((void *) ((cv)->sv_any)))->xcv_start_u.xcv_start; }
    while (0); Perl_save_sptr(((PerlInterpreter *)Perl_get_context()),
    (SV**)&(((0+((((PerlInterpreter
    *)Perl_get_context())->Idefgv))->sv_u.svu_gp)->gp_sv))); for(i = 1 ; i < items
    ; ++i) { ((0+((((PerlInterpreter
    *)Perl_get_context())->Idefgv))->sv_u.svu_gp)->gp_sv) = args[i]; do {
    (((PerlInterpreter *)Perl_get_context())->Iop) = multicall_cop;
    (((PerlInterpreter *)Perl_get_context())->Irunops)(((PerlInterpreter
    *)Perl_get_context())); } while (0); {if (((((*(((PerlInterpreter
    *)Perl_get_context())->Istack_sp)) ? (char)1 : (char)0)) &&
    ((((((*(((PerlInterpreter *)Perl_get_context())->Istack_sp))->sv_flags &
    0x00200000)) ? (char)1 : (char)0)) ? Perl_sv_2bool_flags(((PerlInterpreter
    *)Perl_get_context()), *(((PerlInterpreter *)Perl_get_context())->Istack_sp),2)
    : ( !((*(((PerlInterpreter *)Perl_get_context())->Istack_sp))->sv_flags &
    (0x00000100|0x00000200|0x00000400|0x00000800|
    0x00001000|0x00002000|0x00004000|0x00008000) || (((svtype)((*(((PerlInterpreter
    *)Perl_get_context())->Istack_sp))->sv_flags & 0xff)) == SVt_REGEXP ||
    ((*(((PerlInterpreter *)Perl_get_context())->Istack_sp))->sv_flags &
    (0xff|0x00004000|0x00008000|0x01000000)) == (SVt_PVLV|0x01000000))) ? 0 :
    ((*(((PerlInterpreter *)Perl_get_context())->Istack_sp))->sv_flags &
    0x00000400) ? ( ((XPV*)((*(((PerlInterpreter
    *)Perl_get_context())->Istack_sp)))->sv_any) && ( ((XPV*)((*(((PerlInterpreter
    *)Perl_get_context())->Istack_sp)))->sv_any)->xpv_cur > 1 || (
    ((XPV*)((*(((PerlInterpreter
    *)Perl_get_context())->Istack_sp)))->sv_any)->xpv_cur && *(*(((PerlInterpreter
    *)Perl_get_context())->Istack_sp))->sv_u.svu_pv != '0' ) ) ) :
    ((*(((PerlInterpreter *)Perl_get_context())->Istack_sp))->sv_flags &
    (0x00000100|0x00000200)) ? ( (((*(((PerlInterpreter
    *)Perl_get_context())->Istack_sp))->sv_flags & 0x00000100) && ((XPVIV*)
    (*(((PerlInterpreter *)Perl_get_context())->Istack_sp))->sv_any)->xiv_u.xivu_iv
    != 0) || (((*(((PerlInterpreter *)Perl_get_context())->Istack_sp))->sv_flags &
    0x00000200) && ((XPVNV*) (*(((PerlInterpreter
    *)Perl_get_context())->Istack_sp))->sv_any)->xnv_u.xnv_nv != 0.0)) :
    (Perl_sv_2bool_flags(((PerlInterpreter *)Perl_get_context()),
    *(((PerlInterpreter *)Perl_get_context())->Istack_sp),0)))))) ({ do { cx =
    &((((PerlInterpreter
    *)Perl_get_context())->Icurstackinfo)->si_cxstack)[((((PerlInterpreter
    *)Perl_get_context())->Icurstackinfo)->si_cxix)]; if (! (((*S_CvDEPTHp((const
    CV *)multicall_cv)) = cx->cx_u.cx_blk.blk_u.blku_sub.olddepth)) ) { do {
    S_SvREFCNT_dec(((PerlInterpreter *)Perl_get_context()), ((SV *)((void *)
    (multicall_cv)))); } while (0); } ;; cx = &((((PerlInterpreter
    *)Perl_get_context())->Icurstackinfo)->si_cxstack)[((((PerlInterpreter
    *)Perl_get_context())->Icurstackinfo)->si_cxix)--], newsp = (((PerlInterpreter
    *)Perl_get_context())->Istack_base) + cx->cx_u.cx_blk.blku_oldsp,
    (((PerlInterpreter *)Perl_get_context())->Icurcop) =
    cx->cx_u.cx_blk.blku_oldcop, (((PerlInterpreter
    *)Perl_get_context())->Imarkstack_ptr) = (((PerlInterpreter
    *)Perl_get_context())->Imarkstack) + cx->cx_u.cx_blk.blku_oldmarksp,
    (((PerlInterpreter *)Perl_get_context())->Iscopestack_ix) =
    cx->cx_u.cx_blk.blku_oldscopesp, (((PerlInterpreter
    *)Perl_get_context())->Icurpm) = cx->cx_u.cx_blk.blku_oldpm, gimme =
    cx->cx_u.cx_blk.blku_gimme;; do { SV **sp = (((PerlInterpreter
    *)Perl_get_context())->Istack_sp); PERL_SI * const prev = (((PerlInterpreter
    *)Perl_get_context())->Icurstackinfo)->si_prev; if (!prev) {
    Perl_croak_popstack(); } do { ((XPVAV*) ((((PerlInterpreter
    *)Perl_get_context())->Icurstack))->sv_any)->xav_fill = sp - (((PerlInterpreter
    *)Perl_get_context())->Istack_base); (((PerlInterpreter
    *)Perl_get_context())->Istack_base) = ((prev->si_stack)->sv_u.svu_array);
    (((PerlInterpreter *)Perl_get_context())->Istack_max) = (((PerlInterpreter
    *)Perl_get_context())->Istack_base) + ((XPVAV*)
    (prev->si_stack)->sv_any)->xav_max; sp = (((PerlInterpreter
    *)Perl_get_context())->Istack_sp) = (((PerlInterpreter
    *)Perl_get_context())->Istack_base) + ((XPVAV*)
    (prev->si_stack)->sv_any)->xav_fill; (((PerlInterpreter
    *)Perl_get_context())->Icurstack) = prev->si_stack; } while (0);
    (((PerlInterpreter *)Perl_get_context())->Icurstackinfo) = prev; } while (0);
    do { (((PerlInterpreter *)Perl_get_context())->Itop_env)->je_mustcatch =
    (multicall_oldcatch); } while (0); Perl_pop_scope(((PerlInterpreter
    *)Perl_get_context())); sp = (((PerlInterpreter
    *)Perl_get_context())->Istack_sp); } while (0); do { ((((PerlInterpreter
    *)Perl_get_context())->Istack_base)[ax + (0)] = &(((PerlInterpreter
    *)Perl_get_context())->Isv_yes) ); do { const IV tmpXSoff = (1);
    (((PerlInterpreter *)Perl_get_context())->Istack_sp) = (((PerlInterpreter
    *)Perl_get_context())->Istack_base) + ax + (tmpXSoff - 1); return; } while (0);
    } while (0); }); }; } do { cx = &((((PerlInterpreter
    *)Perl_get_context())->Icurstackinfo)->si_cxstack)[((((PerlInterpreter
    *)Perl_get_context())->Icurstackinfo)->si_cxix)]; if (! (((*S_CvDEPTHp((const
    CV *)multicall_cv)) = cx->cx_u.cx_blk.blk_u.blku_sub.olddepth)) ) { do {
    S_SvREFCNT_dec(((PerlInterpreter *)Perl_get_context()), ((SV *)((void *)
    (multicall_cv)))); } while (0); } ;; cx = &((((PerlInterpreter
    *)Perl_get_context())->Icurstackinfo)->si_cxstack)[((((PerlInterpreter
    *)Perl_get_context())->Icurstackinfo)->si_cxix)--], newsp = (((PerlInterpreter
    *)Perl_get_context())->Istack_base) + cx->cx_u.cx_blk.blku_oldsp,
    (((PerlInterpreter *)Perl_get_context())->Icurcop) =
    cx->cx_u.cx_blk.blku_oldcop, (((PerlInterpreter
    *)Perl_get_context())->Imarkstack_ptr) = (((PerlInterpreter
    *)Perl_get_context())->Imarkstack) + cx->cx_u.cx_blk.blku_oldmarksp,
    (((PerlInterpreter *)Perl_get_context())->Iscopestack_ix) =
    cx->cx_u.cx_blk.blku_oldscopesp, (((PerlInterpreter
    *)Perl_get_context())->Icurpm) = cx->cx_u.cx_blk.blku_oldpm, gimme =
    cx->cx_u.cx_blk.blku_gimme;; do { SV **sp = (((PerlInterpreter
    *)Perl_get_context())->Istack_sp); PERL_SI * const prev = (((PerlInterpreter
    *)Perl_get_context())->Icurstackinfo)->si_prev;  if (!prev) {
    Perl_croak_popstack(); } do { ((XPVAV*) ((((PerlInterpreter
    *)Perl_get_context())->Icurstack))->sv_any)->xav_fill = sp - (((PerlInterpreter
    *)Perl_get_context())->Istack_base); (((PerlInterpreter
    *)Perl_get_context())->Istack_base) = ((prev->si_stack)->sv_u.svu_array);
    (((PerlInterpreter *)Perl_get_context())->Istack_max) = (((PerlInterpreter
    *)Perl_get_context())->Istack_base) + ((XPVAV*)
    (prev->si_stack)->sv_any)->xav_max; sp = (((PerlInterpreter
    *)Perl_get_context())->Istack_sp) = (((PerlInterpreter
    *)Perl_get_context())->Istack_base) + ((XPVAV*)
    (prev->si_stack)->sv_any)->xav_fill; (((PerlInterpreter
    *)Perl_get_context())->Icurstack) = prev->si_stack; } while (0);
    (((PerlInterpreter *)Perl_get_context())->Icurstackinfo) = prev; } while (0);
    do {  (((PerlInterpreter *)Perl_get_context())->Itop_env)->je_mustcatch =
    (multicall_oldcatch); } while (0); Perl_pop_scope(((PerlInterpreter
    *)Perl_get_context())); sp = (((PerlInterpreter
    *)Perl_get_context())->Istack_sp); } while (0); } else do { ((((PerlInterpreter
    *)Perl_get_context())->Istack_base)[ax + (0)] = &(((PerlInterpreter
    *)Perl_get_context())->Isv_no) ); do { const IV tmpXSoff = (1);
    (((PerlInterpreter *)Perl_get_context())->Istack_sp) = (((PerlInterpreter
    *)Perl_get_context())->Istack_base) + ax + (tmpXSoff - 1); return; } while (0);
    } while (0);; do { ((((PerlInterpreter *)Perl_get_context())->Istack_base)[ax +
    (0)] = &(((PerlInterpreter *)Perl_get_context())->Isv_no) ); do { const IV
    tmpXSoff = (1); (((PerlInterpreter *)Perl_get_context())->Istack_sp) =
    (((PerlInterpreter *)Perl_get_context())->Istack_base) + ax + (tmpXSoff - 1);
    return; } while (0); } while (0); }
    #line 547 "MoreUtils.c"

**Comment by rehsack** [comment]
I will check this tomorrow soon. Thanks for submitting.

**Comment by nanis** [comment]
> Do you have the compiler messages for me?

Nothing other than what's contained in the failing test report, I am afraid:

<pre>MoreUtils.xs(370) : error C2059: syntax error : '{'
MoreUtils.xs(370) : error C2143: syntax error : missing ';' before ')'
MoreUtils.xs(370) : error C2059: syntax error : ')'
MoreUtils.xs(370) : error C2065: 'cx' : undeclared identifier
MoreUtils.xs(370) : warning C4047: '=' : 'int' differs in levels of indirection from 'PERL_CONTEXT *'
MoreUtils.xs(370) : error C2065: 'multicall_cv' : undeclared identifier
MoreUtils.xs(370) : error C2223: left of '->cx_u' must point to struct/union
MoreUtils.xs(370) : error C2065: 'newsp' : undeclared identifier
MoreUtils.xs(370) : error C2065: 'gimme' : undeclared identifier
MoreUtils.xs(370) : error C2065: 'multicall_oldcatch' : undeclared identifier
MoreUtils.xs(370) : error C2059: syntax error : 'else'
MoreUtils.xs(370) : error C2059: syntax error : 'while'
MoreUtils.xs(371) : error C2059: syntax error : 'do'
MoreUtils.xs(371) : error C2059: syntax error : 'while'
MoreUtils.xs(372) : error C2059: syntax error : '}'
MoreUtils.c(548) : error C2059: syntax error : 'while'
MoreUtils.c(549) : error C2059: syntax error : '}'
MoreUtils.xs(380) : warning C4244: '=' : conversion from '__int64' to 'I32', possible loss of data
MoreUtils.xs(380) : error C2059: syntax error : '{'
MoreUtils.xs(380) : error C2143: syntax error : missing ';' before ')'
MoreUtils.xs(380) : error C2059: syntax error : ')'
MoreUtils.xs(380) : error C2065: 'cx' : undeclared identifier
MoreUtils.xs(380) : warning C4047: '=' : 'int' differs in levels of indirection from 'PERL_CONTEXT *'
MoreUtils.xs(380) : error C2065: 'multicall_cv' : undeclared identifier
MoreUtils.xs(380) : error C2223: left of '->cx_u' must point to struct/union
MoreUtils.xs(380) : error C2065: 'newsp' : undeclared identifier
MoreUtils.xs(380) : error C2065: 'gimme' : undeclared identifier
MoreUtils.xs(380) : error C2065: 'multicall_oldcatch' : undeclared identifier
MoreUtils.xs(380) : error C2059: syntax error : 'else'
MoreUtils.xs(380) : error C2059: syntax error : 'while'
MoreUtils.xs(381) : error C2059: syntax error : 'do'
MoreUtils.xs(381) : error C2059: syntax error : 'while'
MoreUtils.xs(382) : error C2059: syntax error : '}'
MoreUtils.c(568) : error C2059: syntax error : 'while'
MoreUtils.c(569) : error C2059: syntax error : '}'
MoreUtils.xs(391) : warning C4244: '=' : conversion from '__int64' to 'I32', possible loss of data
MoreUtils.xs(391) : error C2059: syntax error : '{'
MoreUtils.xs(391) : error C2143: syntax error : missing ';' before ')'
MoreUtils.xs(391) : error C2059: syntax error : ')'
MoreUtils.xs(391) : error C2065: 'cx' : undeclared identifier
MoreUtils.xs(391) : warning C4047: '=' : 'int' differs in levels of indirection from 'PERL_CONTEXT *'
MoreUtils.xs(391) : error C2065: 'multicall_cv' : undeclared identifier
MoreUtils.xs(391) : error C2223: left of '->cx_u' must point to struct/union
MoreUtils.xs(391) : error C2065: 'newsp' : undeclared identifier
MoreUtils.xs(391) : error C2065: 'gimme' : undeclared identifier
MoreUtils.xs(391) : error C2065: 'multicall_oldcatch' : undeclared identifier
MoreUtils.xs(391) : error C2059: syntax error : 'else'
MoreUtils.xs(391) : error C2059: syntax error : 'while'
MoreUtils.xs(392) : error C2059: syntax error : 'do'
MoreUtils.xs(392) : error C2059: syntax error : 'while'
MoreUtils.xs(393) : error C2059: syntax error : '}'
MoreUtils.c(588) : error C2059: syntax error : 'while'
MoreUtils.c(589) : error C2059: syntax error : '}'
MoreUtils.xs(401) : warning C4244: '=' : conversion from '__int64' to 'I32', possible loss of data
MoreUtils.xs(401) : error C2059: syntax error : '{'
MoreUtils.xs(401) : error C2143: syntax error : missing ';' before ')'
MoreUtils.xs(401) : error C2059: syntax error : ')'
MoreUtils.xs(401) : error C2065: 'cx' : undeclared identifier
MoreUtils.xs(401) : warning C4047: '=' : 'int' differs in levels of indirection from 'PERL_CONTEXT *'
MoreUtils.xs(401) : error C2065: 'multicall_cv' : undeclared identifier
MoreUtils.xs(401) : error C2223: left of '->cx_u' must point to struct/union
MoreUtils.xs(401) : error C2065: 'newsp' : undeclared identifier
MoreUtils.xs(401) : error C2065: 'gimme' : undeclared identifier
MoreUtils.xs(401) : error C2065: 'multicall_oldcatch' : undeclared identifier
MoreUtils.xs(401) : error C2059: syntax error : 'else'
MoreUtils.xs(401) : error C2059: syntax error : 'while'
MoreUtils.xs(402) : error C2059: syntax error : 'do'
MoreUtils.xs(402) : error C2059: syntax error : 'while'
MoreUtils.xs(403) : error C2059: syntax error : '}'
MoreUtils.c(608) : error C2059: syntax error : 'while'
MoreUtils.c(609) : error C2059: syntax error : '}'
MoreUtils.xs(412) : warning C4244: '=' : conversion from '__int64' to 'I32', possible loss of data
MoreUtils.xs(412) : error C2059: syntax error : '{'
MoreUtils.xs(412) : error C2143: syntax error : missing ';' before ')'
MoreUtils.xs(412) : error C2059: syntax error : ')'
MoreUtils.xs(412) : error C2059: syntax error : 'do'
MoreUtils.xs(412) : error C2059: syntax error : 'while'
MoreUtils.xs(412) : error C2059: syntax error : '}'
MoreUtils.xs(413) : error C2059: syntax error : 'if'
MoreUtils.xs(414) : error C2059: syntax error : 'while'
MoreUtils.xs(415) : error C2059: syntax error : 'do'
MoreUtils.xs(415) : error C2059: syntax error : 'while'
MoreUtils.xs(416) : error C2059: syntax error : '}'
MoreUtils.c(631) : error C2059: syntax error : 'while'
MoreUtils.c(632) : error C2059: syntax error : '}'
MoreUtils.xs(424) : warning C4244: '=' : conversion from '__int64' to 'I32', possible loss of data
MoreUtils.xs(424) : error C2059: syntax error : '{'
MoreUtils.xs(424) : error C2143: syntax error : missing ';' before ')'
MoreUtils.xs(424) : error C2059: syntax error : ')'
MoreUtils.xs(424) : error C2065: 'cx' : undeclared identifier
MoreUtils.xs(424) : warning C4047: '=' : 'int' differs in levels of indirection from 'PERL_CONTEXT *'
MoreUtils.xs(424) : error C2065: 'multicall_cv' : undeclared identifier
MoreUtils.xs(424) : error C2223: left of '->cx_u' must point to struct/union
MoreUtils.xs(424) : error C2065: 'newsp' : undeclared identifier
MoreUtils.xs(424) : error C2065: 'gimme' : undeclared identifier
MoreUtils.xs(424) : error C2065: 'multicall_oldcatch' : undeclared identifier
MoreUtils.xs(424) : error C2059: syntax error : 'else'
MoreUtils.xs(424) : error C2059: syntax error : 'while'
MoreUtils.xs(425) : error C2059: syntax error : 'do'
MoreUtils.xs(425) : error C2059: syntax error : 'while'
MoreUtils.xs(426) : error C2059: syntax error : '}'
MoreUtils.c(651) : error C2059: syntax error : 'while'
MoreUtils.c(652) : error C2059: syntax error : '}'
MoreUtils.xs(434) : warning C4244: '=' : conversion from '__int64' to 'I32', possible loss of data
MoreUtils.xs(434) : error C2059: syntax error : '{'
MoreUtils.xs(434) : error C2143: syntax error : missing ';' before ')'
MoreUtils.xs(434) : error C2059: syntax error : ')'
MoreUtils.xs(434) : error C2065: 'cx' : undeclared identifier
MoreUtils.xs(434) : warning C4047: '=' : 'int' differs in levels of indirection from 'PERL_CONTEXT *'
MoreUtils.xs(434) : error C2065: 'multicall_cv' : undeclared identifier
MoreUtils.xs(434) : error C2223: left of '->cx_u' must point to struct/union
MoreUtils.xs(434) : error C2065: 'newsp' : undeclared identifier
MoreUtils.xs(434) : error C2065: 'gimme' : undeclared identifier
MoreUtils.xs(434) : fatal error C1003: error count exceeds 100; stopping compilation</pre>

**Comment by rehsack** [comment]
Sorry for asking, it's late.

**Comment by rehsack** [comment]
Shipped 0.409_001 for testing - please tell me whether it helps (I tried MSVC 2013 and SunPro 12.3)

**Comment by nanis** [comment]
I did not look at the code, but it seems to work ;-)

<pre>C:\> cpanm http://search.cpan.org/CPAN/authors/id/R/RE/REHSACK/List-MoreUtils-0.409_001.tar.gz
--> Working on http://search.cpan.org/CPAN/authors/id/R/RE/REHSACK/List-MoreUtils-0.409_001.tar.gz
Fetching http://search.cpan.org/CPAN/authors/id/R/RE/REHSACK/List-MoreUtils-0.409_001.tar.gz ... OK
Configuring List-MoreUtils-0.409_001 ... OK
Building and testing List-MoreUtils-0.409_001 ... OK
Successfully installed List-MoreUtils-0.409_001
1 distribution installed</pre>

**Comment by nanis** [comment]
OK, I see ... Nice work-around. Thank you very much for your work.
